
package de.bio.hazard.securemessage.webservice.basisinfo;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BasisInfoWebservice", targetNamespace = "http://webservice.securemessage.hazard.bio.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BasisInfoWebservice {


    /**
     * 
     * @return
     *     returns de.bio.hazard.securemessage.webservice.basisinfo.ServerPublicKeyDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerPublicKey", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", className = "de.bio.hazard.securemessage.webservice.basisinfo.GetServerPublicKey")
    @ResponseWrapper(localName = "getServerPublicKeyResponse", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", className = "de.bio.hazard.securemessage.webservice.basisinfo.GetServerPublicKeyResponse")
    @Action(input = "http://webservice.securemessage.hazard.bio.de/BasisInfoWebservice/getServerPublicKeyRequest", output = "http://webservice.securemessage.hazard.bio.de/BasisInfoWebservice/getServerPublicKeyResponse")
    public ServerPublicKeyDTO getServerPublicKey();

}
