
package de.bio.hazard.securemessage.webservice.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationWebservice", targetNamespace = "http://webservice.securemessage.hazard.bio.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationWebservice {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewUser", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", className = "de.bio.hazard.securemessage.webservice.authentication.AddNewUser")
    @ResponseWrapper(localName = "addNewUserResponse", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", className = "de.bio.hazard.securemessage.webservice.authentication.AddNewUserResponse")
    @Action(input = "http://webservice.securemessage.hazard.bio.de/AuthenticationWebservice/addNewUserRequest", output = "http://webservice.securemessage.hazard.bio.de/AuthenticationWebservice/addNewUserResponse")
    public void addNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        NewUserWebserviceDTO arg0);

}
