
package de.bio.hazard.securemessage.webservice.authentication;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticationWebserviceService", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", wsdlLocation = "http://localhost:8080/authenticationWebservice?wsdl")
public class AuthenticationWebserviceService
    extends Service
{

    private final static URL AUTHENTICATIONWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONWEBSERVICESERVICE_EXCEPTION;
    private final static QName AUTHENTICATIONWEBSERVICESERVICE_QNAME = new QName("http://webservice.securemessage.hazard.bio.de/", "AuthenticationWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/authenticationWebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONWEBSERVICESERVICE_WSDL_LOCATION = url;
        AUTHENTICATIONWEBSERVICESERVICE_EXCEPTION = e;
    }

    public AuthenticationWebserviceService() {
        super(__getWsdlLocation(), AUTHENTICATIONWEBSERVICESERVICE_QNAME);
    }

    public AuthenticationWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONWEBSERVICESERVICE_QNAME, features);
    }

    public AuthenticationWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONWEBSERVICESERVICE_QNAME);
    }

    public AuthenticationWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONWEBSERVICESERVICE_QNAME, features);
    }

    public AuthenticationWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticationWebservice
     */
    @WebEndpoint(name = "AuthenticationWebservicePort")
    public AuthenticationWebservice getAuthenticationWebservicePort() {
        return super.getPort(new QName("http://webservice.securemessage.hazard.bio.de/", "AuthenticationWebservicePort"), AuthenticationWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationWebservice
     */
    @WebEndpoint(name = "AuthenticationWebservicePort")
    public AuthenticationWebservice getAuthenticationWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.securemessage.hazard.bio.de/", "AuthenticationWebservicePort"), AuthenticationWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONWEBSERVICESERVICE_EXCEPTION!= null) {
            throw AUTHENTICATIONWEBSERVICESERVICE_EXCEPTION;
        }
        return AUTHENTICATIONWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
