
package de.bio.hazard.securemessage.webservice.authentication;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DeviceNotFoundException", targetNamespace = "http://webservice.securemessage.hazard.bio.de/")
public class DeviceNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DeviceNotFoundException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DeviceNotFoundException_Exception(String message, DeviceNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DeviceNotFoundException_Exception(String message, DeviceNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.bio.hazard.securemessage.webservice.authentication.DeviceNotFoundException
     */
    public DeviceNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
