
package de.bio.hazard.securemessage.webservice.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserWebserviceService", targetNamespace = "http://webservice.securemessage.hazard.bio.de/", wsdlLocation = "http://localhost:8080/userWebservice?wsdl")
public class UserWebserviceService
    extends Service
{

    private final static URL USERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException USERWEBSERVICESERVICE_EXCEPTION;
    private final static QName USERWEBSERVICESERVICE_QNAME = new QName("http://webservice.securemessage.hazard.bio.de/", "UserWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/userWebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWEBSERVICESERVICE_WSDL_LOCATION = url;
        USERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public UserWebserviceService() {
        super(__getWsdlLocation(), USERWEBSERVICESERVICE_QNAME);
    }

    public UserWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWEBSERVICESERVICE_QNAME, features);
    }

    public UserWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, USERWEBSERVICESERVICE_QNAME);
    }

    public UserWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWEBSERVICESERVICE_QNAME, features);
    }

    public UserWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWebservice
     */
    @WebEndpoint(name = "UserWebservicePort")
    public UserWebservice getUserWebservicePort() {
        return super.getPort(new QName("http://webservice.securemessage.hazard.bio.de/", "UserWebservicePort"), UserWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebservice
     */
    @WebEndpoint(name = "UserWebservicePort")
    public UserWebservice getUserWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.securemessage.hazard.bio.de/", "UserWebservicePort"), UserWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw USERWEBSERVICESERVICE_EXCEPTION;
        }
        return USERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
