
package de.bio.hazard.securemessage.webservice.message;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EncryptionExceptionBiohazard", targetNamespace = "http://webservice.securemessage.hazard.bio.de/")
public class EncryptionExceptionBiohazard_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EncryptionExceptionBiohazard faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EncryptionExceptionBiohazard_Exception(String message, EncryptionExceptionBiohazard faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EncryptionExceptionBiohazard_Exception(String message, EncryptionExceptionBiohazard faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.bio.hazard.securemessage.webservice.message.EncryptionExceptionBiohazard
     */
    public EncryptionExceptionBiohazard getFaultInfo() {
        return faultInfo;
    }

}
